apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-metastore-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repoUrl | quote }}
    targetRevision: {{ .Values.git.revision | quote }}
    path: infra/helm-charts/postgres-metastore
    helm:
      values: |
        persistence:
          storageClass: standard
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
