apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    targetRevision: 2.5.0
    chart: spark-operator
    helm:
      skipCrds: false
      values: |
        webhook:
          enable: true
        spark:
          jobNamespaces:
            - data-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
