nameOverride: minio
fullnameOverride: minio

replicaCount: 1

image:
  repository: ghcr.io/l33tlamer/minio-backup
  digest: sha256:a1ea29fa28355559ef137d71fc570e508a214ec84ff8083e39bc5428980b015e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

credentialsSecretName: data-master-minio-secret

clientImage:
  repository: bitnamilegacy/minio-client
  digest: sha256:1560800eb0449bd1605e1cd8858227df482b03fd14f4efd51f641f6f77eb788d
  pullPolicy: IfNotPresent

# Persistence
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: ""

# Resources
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 200m

extraEnv: []

# Probes
livenessProbe:
  httpGet:
    path: /minio/health/live
    port: 9000
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /minio/health/ready
    port: 9000
  initialDelaySeconds: 5
  periodSeconds: 10

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Service account
serviceAccount:
  create: true
  name: ""

# Node selector, tolerations, affinity
nodeSelector: {}
tolerations: []
affinity: {}
