apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-metastore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgres-metastore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "postgres-metastore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
